Repository erlete/algebruh, pull requests merged in 2023-08, with the labels that each got.

#18 Search methods implementation
  .vscode/settings.json
  .vscode/tasks.json
  package-lock.json
  package.json
  src/image_solver.html
  src/index.html
  src/media/image_solver.png
  src/modules/difflib-browser.js
  src/renderers/image_solver.js
  src/renderers/test.js
  src/renderers/text_solver.js
  src/styles/output.css
  src/text_solver.html
  src/usage.html
  tailwind.config.js
Labels: enhancement

#19 General improvements
  README.md
  package-lock.json
  package.json
  src/image_solver.html
  src/index.html
  src/index.js
  src/media/image_solver.png
  src/modules/commons.js
  src/renderers/image_solver.js
  src/renderers/index.js
  src/renderers/test.js
  src/renderers/text_solver.js
  src/styles/output.css
  src/styles/template.css
  src/text_solver.html
  src/usage.html
Labels: documentation, enhancement

#21 Minor fixes 2
  src/image.html
  src/image_solver.html
  src/index.html
  src/renderers/image.js
  src/renderers/text.js
  src/styles/output.css
  src/text.html
Labels: bug

#22 DevTools implementation
  .vscode/tasks.json
  CONTRIBUTING.md
  README.md
  devtools/index.html
  devtools/index.js
  devtools/media/information.svg
  devtools/modules/commons.js
  devtools/modules/difflib-browser.js
  devtools/modules/remove-duplicates.js
  devtools/styles/output.css
  devtools/styles/template.css
Labels: enhancement

#24 Updated questions.json
  src/databases/questions.json
Labels: database-update

#23 Update Question format
  src/databases/questions.json
Labels: database-update

#25 General improvements
  .vscode/tasks.json
  devtools/index.html
  devtools/media/icon.ico
  devtools/modules/commons.js
  devtools/modules/tesseract.min.js
  devtools/modules/tesseract.min.js.map
  devtools/styles/output.css
  package-lock.json
  package.json
  scripts/compileCSS/unix.sh
  scripts/compileCSS/windows.bat
  scripts/startLocalServer/unix.sh
  scripts/startLocalServer/windows.bat
  src/image.html
  src/index.html
  src/media/gh-icon.png
  src/modules/commons.js
  src/modules/tesseract.min.js
  src/modules/tesseract.min.js.map
  src/renderers/image.js
  src/renderers/text.js
  src/styles/output.css
  src/styles/template.css
  src/text.html
Labels: documentation, enhancement

#26 General enhancements
  devtools/add.html
  devtools/index.html
  devtools/media/gh-icon.png
  devtools/media/icon.png
  devtools/modify.html
  devtools/modules/commons.js
  devtools/renderers/add.js
  devtools/renderers/modify.js
  devtools/styles/output.css
  devtools/styles/template.css
  src/databases/questions.json
  src/image.html
  src/index.html
  src/renderers/index.js
  src/styles/output.css
  src/styles/template.css
  src/text.html
  tailwind.config.js
Labels: bug, documentation, enhancement, database-update

#27 Minor updates
  devtools/add.html
  devtools/index.html
  devtools/modify.html
  src/image.html
  src/index.html
  src/index.js
  src/media/favicon.ico
  src/media/site-preview.png
  src/styles/output.css
  src/text.html
Labels: bug, enhancement
